# Generated by Django 4.2.16 on 2024-12-10 11:55

from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='分类ID')),
                ('category_name_en', models.CharField(max_length=100, verbose_name='英文名称')),
                ('category_name_zh', models.CharField(max_length=100, verbose_name='中文名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分类描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to=gallery.models.category_image_path, verbose_name='分类图片')),
                ('rank_id', models.IntegerField(default=0, verbose_name='排序ID')),
                ('original_data', models.JSONField(blank=True, null=True, verbose_name='原始数据')),
                ('level', models.IntegerField(choices=[(1, '一级分类'), (2, '二级分类'), (3, '三级分类')], default=1, verbose_name='分类层级')),
                ('is_last_level', models.BooleanField(default=False, verbose_name='是否最后一级')),
                ('status', models.IntegerField(choices=[(1, '启用'), (0, '禁用')], default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='gallery.category', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'gallery_category',
                'ordering': ['rank_id', 'id'],
            },
        ),
    ]
