# Generated by Django 4.2.16 on 2024-12-10 13:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_spu'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='SKU ID')),
                ('sku_code', models.CharField(help_text='唯一的SKU标识码', max_length=50, unique=True, verbose_name='SKU编码')),
                ('sku_name', models.CharField(help_text='产品具体型号名称', max_length=200, verbose_name='SKU名称')),
                ('provider_name', models.CharField(help_text='产品供应商', max_length=100, verbose_name='供应商名称')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='产品单价（元）', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='单价')),
                ('weight', models.DecimalField(decimal_places=3, help_text='产品重量（kg）', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='重量')),
                ('plating_process', models.CharField(choices=[('none', '无电镀'), ('gold', '镀金'), ('silver', '镀银'), ('nickel', '镀镍'), ('chrome', '镀铬'), ('copper', '镀铜'), ('other', '其他')], default='none', help_text='产品电镀工艺', max_length=20, verbose_name='电镀工艺')),
                ('length', models.DecimalField(decimal_places=2, help_text='产品长度（mm）', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='长度')),
                ('width', models.DecimalField(decimal_places=2, help_text='产品宽度（mm）', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='宽度')),
                ('height', models.DecimalField(decimal_places=2, help_text='产品高度（mm）', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='高度')),
                ('other_dimensions', models.CharField(blank=True, help_text='其他尺寸规格描述', max_length=200, null=True, verbose_name='其他尺寸')),
                ('material', models.CharField(help_text='产品材质', max_length=100, verbose_name='材质')),
                ('img_url', models.ImageField(blank=True, help_text='产品图片', null=True, upload_to='skus', verbose_name='产品图片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.BooleanField(default=True, help_text='是否启用', verbose_name='状态')),
                ('spu', models.ForeignKey(help_text='产品所属SPU', on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='gallery.spu', verbose_name='所属SPU')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKU列表',
                'db_table': 'gallery_sku',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sku_code'], name='gallery_sku_sku_cod_78e1d5_idx'), models.Index(fields=['spu'], name='gallery_sku_spu_id_d5bb39_idx'), models.Index(fields=['created_at'], name='gallery_sku_created_d8b747_idx')],
            },
        ),
    ]
