# Generated by Django 4.2.16 on 2024-12-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sku',
            options={'ordering': ['-created_at'], 'permissions': [('sync_sku', 'Can synchronize SKU data')], 'verbose_name': 'SKU', 'verbose_name_plural': 'SKU列表'},
        ),
        migrations.AlterField(
            model_name='sku',
            name='provider_name',
            field=models.CharField(blank=True, default='无', max_length=100, verbose_name='供应商'),
        ),
    ]
