# Generated by Django 4.2.16 on 2024-12-11 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_sku_options_alter_sku_provider_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='产品高度（mm）', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='高度'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='产品长度（mm）', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='长度'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='material',
            field=models.CharField(blank=True, default='无', help_text='产品材质', max_length=100, verbose_name='材质'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='plating_process',
            field=models.CharField(blank=True, choices=[('none', '无电镀'), ('gold', '镀金'), ('silver', '镀银'), ('nickel', '镀镍'), ('chrome', '镀铬'), ('copper', '镀铜'), ('other', '其他')], default='none', help_text='产品电镀工艺', max_length=20, verbose_name='电镀工艺'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='产品单价（元）', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='产品重量（kg）', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='重量'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='产品宽度（mm）', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='宽度'),
        ),
    ]
