# Generated by Django 4.2.16 on 2024-12-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_sku_height_alter_sku_length_alter_sku_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='color',
            field=models.CharField(blank=True, default='无', help_text='产品颜色', max_length=50, verbose_name='颜色'),
        ),
    ]
